/**
 * Builds a structured recommendation object from engine results.
 */

import { evaluateDischarge, evaluateMultipleConditions } from './decision-engine.js';
import { computeScores } from './scoring.js';

/**
 * Build a full recommendation for one or more selected conditions.
 * @param {Array} selectedConditions - Array of { conditionId, subtypeId, rules, answers }
 * @returns {Object} Final recommendation
 */
export function buildRecommendation(selectedConditions) {
  const conditionResults = [];

  for (const sc of selectedConditions) {
    const result = evaluateDischarge(sc.rules, sc.answers);
    result.conditionName = sc.conditionName || sc.conditionId;
    result.subtypeName = sc.subtypeName || null;
    result.scores = computeScores(sc.conditionId, sc.answers);
    conditionResults.push(result);
  }

  let final;
  if (conditionResults.length === 1) {
    final = conditionResults[0];
    final.conditionResults = conditionResults;
  } else {
    final = evaluateMultipleConditions(conditionResults);
    // Collect all scores
    final.scores = conditionResults.flatMap(cr => cr.scores || []);
  }

  // Add metadata
  final.date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  final.timestamp = new Date().toISOString();

  // Build readable summary
  final.summary = buildSummaryText(final);

  return final;
}

function buildSummaryText(result) {
  const lines = [];
  lines.push('CARDIOLOGY CONTINUITY CLINIC — DISCHARGE ASSESSMENT');
  lines.push(`Date: ${result.date}`);
  lines.push('');

  // Conditions evaluated
  if (result.conditionResults) {
    lines.push('Conditions Evaluated:');
    for (const cr of result.conditionResults) {
      const name = cr.subtypeName ? `${cr.conditionName} — ${cr.subtypeName}` : cr.conditionName;
      lines.push(`  • ${name}: ${formatRecommendation(cr.recommendation)}${cr.interval ? ` (${cr.interval} months)` : ''}`);
    }
    lines.push('');
  }

  // Overall recommendation
  lines.push(`RECOMMENDATION: ${formatRecommendation(result.recommendation)}`);
  if (result.interval) {
    lines.push(`Suggested Follow-up: ${result.interval} month${result.interval !== 1 ? 's' : ''}`);
  }
  lines.push('');

  // Reasons
  if (result.reasons && result.reasons.length > 0) {
    lines.push('Key Factors:');
    for (const r of result.reasons) {
      lines.push(`  • ${r}`);
    }
    lines.push('');
  }

  // PCP precautions
  if (result.precautions && result.precautions.length > 0) {
    lines.push('PCP Instructions / Return Precautions:');
    for (const p of result.precautions) {
      lines.push(`  • ${p}`);
    }
    lines.push('');
  }

  // Risk scores
  if (result.scores && result.scores.length > 0) {
    lines.push('Risk Scores:');
    for (const s of result.scores) {
      lines.push(`  • ${s.name}: ${s.score}/${s.maxScore} — ${s.interpretation}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by CardioDischarge — Clinical decision support only.');
  lines.push('Final decisions rest with the treating physician.');

  return lines.join('\n');
}

function formatRecommendation(rec) {
  switch (rec) {
    case 'discharge': return 'SAFE TO DISCHARGE TO PCP';
    case 'continue': return 'CONTINUE CARDIOLOGY FOLLOW-UP';
    case 'closer': return 'NEEDS CLOSER FOLLOW-UP';
    default: return rec.toUpperCase();
  }
}
